trigger:
  batch: true
  branches:
    include:
    - master

pool:
  name: Default

resources:
  repositories:
    - repository: templates
      type: git
      name: DevShared/Templates

variables:
  - name: buildConfiguration
    value: 'Release'

steps:
  - task: DotNetCoreCLI@2
    displayName: 'Build'
    inputs:
      command: build
      projects: '**/*.csproj'
      arguments: '--configuration $(BuildConfiguration)'

  - template: steps/dotnet-test-and-publish-results.yml@templates
